# -*- coding: utf-8 -*-
"""Coursework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xG482D9BcO6wO5qN-QEcTGuDDvlYP8VZ
"""

import pandas as pd
import torch as nn

class Generator(nn.Module):

    def __init__(self, input_length, ):
        super(Generator, self).__init__()
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.batch_size = batch_size
        self.num_layers = num_layers

        self.dense = torch.nn.Linear(self.code_size, 7*7*256, bias=False)
        self.lstm = nn.LSTM()

    def forward(self, x):
        x = self.dense(x)
        x = self.lstm(x)
        x = x.view(-1, ?)
        return x


class Discriminator(nn.Module):
    def __init__(self, input_length, ):
        super(Discriminator, self).__init__()
 
        self.lstm = nn.LSTM()
        self.softmax = nn.SoftMax()

    def forward(self, x):
        x = x.view(-1, ?)
        x = self.lstm(x)
        x = self.softmax(x)

df = pd.read_csv("https://ida191.csc.fi:4430/download?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjI4MzgxNzgsImRhdGFzZXQiOiI3M2ViNDhkNy00ZGJjLTRhMTAtYTUyYS1kYTc0NWI0N2E2NDkiLCJwYWNrYWdlIjoiNzNlYjQ4ZDctNGRiYy00YTEwLWE1MmEtZGE3NDViNDdhNjQ5X3NfbDdqOXRzLnppcCJ9.lVGZwLkcFxUK34QDttZDDUqw0CJ3gTEoAtLcnddC1DM&dataset=73eb48d7-4dbc-4a10-a52a-da745b47a649&package=73eb48d7-4dbc-4a10-a52a-da745b47a649_s_l7j9ts.zip")

df.head()

!pip install zipfile

from io import BytesIO
from zipfile import ZipFile
import pandas
import requests

url = "https://ida191.csc.fi:4430/download?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjI4MzgxNzgsImRhdGFzZXQiOiI3M2ViNDhkNy00ZGJjLTRhMTAtYTUyYS1kYTc0NWI0N2E2NDkiLCJwYWNrYWdlIjoiNzNlYjQ4ZDctNGRiYy00YTEwLWE1MmEtZGE3NDViNDdhNjQ5X3NfbDdqOXRzLnppcCJ9.lVGZwLkcFxUK34QDttZDDUqw0CJ3gTEoAtLcnddC1DM&dataset=73eb48d7-4dbc-4a10-a52a-da745b47a649&package=73eb48d7-4dbc-4a10-a52a-da745b47a649_s_l7j9ts.zip"

file_name = "/content/published/BenchmarkDatasets/BenchmarkDatasets.zip"

with ZipFile(file_name, 'r') as zip:
   zip.printdir()

zip.extract('BenchmarkDatasets/Auction/1.Auction_Zscore/Auction_Zscore_Testing/Test_Dst_Auction_ZScore_CF_1.txt')

pd.read_csv("/content/BenchmarkDatasets/Auction/1.Auction_Zscore/Auction_Zscore_Testing", sep="\t")

